#!/usr/bin/env bash
# pre-compact-preserve.sh
#
# Runs before Claude Code performs a context compaction. Writes a compact
# summary of the active phase state to a file that the compaction process
# preserves (via the PreCompact event hook payload mechanism).
#
# This prevents Phase 3/4 mid-build state from being lost when context fills.
#
# Quality Contract: QC.4b (context window discipline).
# Architectural Principle: AP.7 (lazy load, against compaction collapsing
# essential phase state).

set -uo pipefail

LOG_DIR="${HOME}/.claude-harness"
LOG_FILE="${LOG_DIR}/hook.log"
mkdir -p "${LOG_DIR}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PRESERVE_FILE="${REPO_ROOT}/phase-outputs/.compact-preserve.md"

log() {
  printf '%s\t%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >> "${LOG_FILE}"
}

# Ensure phase-outputs/ exists (it is gitignored).
mkdir -p "${REPO_ROOT}/phase-outputs"

# Determine the active phase by looking at the most recently modified file
# in phase-outputs/. This is a heuristic, not authoritative; the phase
# prompts could write a phase ID file instead, which would be more robust.

ACTIVE_PHASE_FILE="$(find "${REPO_ROOT}/phase-outputs" -type f -name '*.md' \
  -not -name '.compact-preserve.md' \
  -exec stat -f '%m %N' {} \; 2>/dev/null | \
  sort -rn | head -n1 | awk '{print $2}' || true)"

if [[ -z "${ACTIVE_PHASE_FILE}" || ! -f "${ACTIVE_PHASE_FILE}" ]]; then
  log "SKIP no active phase file in phase-outputs/"
  exit 0
fi

ACTIVE_PHASE_NAME="$(basename "${ACTIVE_PHASE_FILE}" .md)"

# Write a compact preservation file. The next session start can read it.
cat > "${PRESERVE_FILE}" <<EOF
# Compaction preservation marker

Generated by pre-compact-preserve.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ).

Active phase at compaction time: ${ACTIVE_PHASE_NAME}
Active phase file: ${ACTIVE_PHASE_FILE}

When the next session starts, the active-phase file above should be re-read
to restore context. The session-start hook surfaces this preservation marker.
EOF

log "PRESERVED phase=${ACTIVE_PHASE_NAME}"
exit 0
